import { Navbar } from '@/app/Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/app/Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AyAI Crop Limited',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
